ARG NODE_BASE=acr-xiaojuntech-registry-vpc.cn-beijing.cr.aliyuncs.com/xiaojuntech/node:20-alpine

FROM ${NODE_BASE}

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk add --no-cache bash curl docker-cli docker-compose util-linux

WORKDIR /app

COPY scripts/webhook-server.js ./scripts/webhook-server.js

CMD ["node", "scripts/webhook-server.js"]
